# Generated by Django 2.1.3 on 2019-10-25 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='basicAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bot_basic_auth',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('activation_date', models.DateField(null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Y', max_length=1)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=50)),
                ('client_code', models.CharField(max_length=10)),
                ('odata_system_url', models.CharField(max_length=100)),
                ('auth_type', models.CharField(default='', max_length=1)),
                ('integration_sys', models.CharField(max_length=50)),
                ('cust_id', models.ForeignKey(db_column='cust_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='masters.Customer')),
            ],
            options={
                'db_table': 'bot_customer_systems',
            },
        ),
        migrations.CreateModel(
            name='Erp',
            fields=[
                ('erp_id', models.AutoField(primary_key=True, serialize=False)),
                ('erp_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bot_erp',
            },
        ),
        migrations.CreateModel(
            name='oAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_url', models.CharField(max_length=255)),
                ('headers', models.TextField()),
                ('payload', models.TextField()),
                ('cust_system_id', models.ForeignKey(db_column='cust_system_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='masters.CustomerSystem')),
            ],
            options={
                'db_table': 'bot_oauth',
            },
        ),
        migrations.CreateModel(
            name='TcodeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bot_tcode_cat',
            },
        ),
        migrations.AddField(
            model_name='customersystem',
            name='erp_id',
            field=models.ForeignKey(db_column='erp_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='masters.Erp'),
        ),
        migrations.AddField(
            model_name='basicauth',
            name='cust_system_id',
            field=models.ForeignKey(db_column='cust_system_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='masters.CustomerSystem'),
        ),
    ]
