# Generated by Django 2.1.3 on 2019-11-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.TextField()),
                ('bot_id', models.TextField()),
                ('status', models.TextField(max_length=1)),
                ('entry_date', models.DateField(null=True)),
                ('cust_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='masters.Customer')),
            ],
            options={
                'db_table': 'bot_task_schedule',
            },
        ),
    ]
